server:
  port: 10001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: aservice
          uri: lb://aservice
          predicates:
            - Path=/aservice/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


