server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: aservice
          uri: lb://aservice
          predicates:
            - Path=/aservice/**
    nacos:
      discovery:
        server-addr: 192.168.65.1:8848


