# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 8  for x64
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        architecture: x64
    - name: ls workdir
      run: ls
      shell: bash  
    - name: Build with Maven    
      run: mvn package
      #working-directory: /home/runner/work/weifuwu
