# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    #- name: Set up JDK 8  for x64
    #  uses: actions/setup-java@v2
    #  with:
    #    java-version: '8'
    #    distribution: 'adopt'
    #    architecture: x64 
    #- name: Build with Maven    
    #  run: mvn -B package --file pom.xml
    - name: Push gateway to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: /home/runner/work/weifuwu/weifuwu/gateway-service/Dockerfile
        path: /home/runner/work/weifuwu/weifuwu
        registry: docker.pkg.github.com
        repository: yinchuang/weifuwu/gateway
        tag_with_ref: true

    - name: Push aservice to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: /home/runner/work/weifuwu/weifuwu/a-service/Dockerfile
        path: /home/runner/work/weifuwu/weifuwu
        registry: docker.pkg.github.com
        repository: yinchuang/weifuwu/aservice
        tag_with_ref: true

    - name: Push bservice to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: /home/runner/work/weifuwu/weifuwu/b-service/Dockerfile
        path: /home/runner/work/weifuwu/weifuwu
        registry: docker.pkg.github.com
        repository: yinchuang/weifuwu/bservice
        tag_with_ref: true

    - name: Push cservice to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: /home/runner/work/weifuwu/weifuwu/c-service/Dockerfile
        path: /home/runner/work/weifuwu/weifuwu
        registry: docker.pkg.github.com
        repository: yinchuang/weifuwu/cservice
        tag_with_ref: true

